language: go
go:
        - 1.14.x
        - 1.15.x
        - stable
script:
        - go get -t ./...
        - go get -u golang.org/x/lint/golint
        - go test ./...
        - CGO_ENABLED=1 go test -race ./...
        - go vet ./...
        - diff -u <(echo -n) <(gofmt -d -s .)
        - diff -u <(echo -n) <(./internal/scripts/autogen_licences.sh .)
        - diff -u <(echo -n) <(golint ./...)
env:
  global:
        - CGO_ENABLED=0
