language: go
go:
        #- 1.16.x
        #- 1.17.x
        - stable
before_install:
        - go install golang.org/x/tools/cmd/cover@latest
        - go install github.com/mattn/goveralls@latest
        - go install golang.org/x/lint/golint@latest
script:
        - go get -t ./...
        # Temporarily set -mod=mod to allow modification of go.mod and go.sum.
        # This seems to be caused by a sum missing in the tcell dependency and
        # should be removed when no longer needed.
        - go test -v -covermode=count -coverprofile=coverage.out -mod=mod ./...
        - CGO_ENABLED=1 go test -mod=mod -race ./...
        - go vet ./...
        #- diff -u <(echo -n) <(gofmt -d -s .)
        - diff -u <(echo -n) <(./private/scripts/autogen_licences.sh .)
        - diff -u <(echo -n) <(golint ./...)
env:
  global:
        - CGO_ENABLED=0
